spring.application.name=discovery-service
server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

rabbitmq.exchange.log=log-exchange
rabbitmq.routingkey.log=log-routing-key
